### ISSUE TITLE
Question - expose the Traefik UI?

### ISSUE THREAD

**Issue by dstroot** [patrickeasters/traefik-k8s-tls-example#1]
Do you use the traefik UI at all?  This does not seem to expose it - or does it?

**Comment by patrickeasters** [comment]
Dan, I haven't personally used it, but it's pretty easy to configure.

First, you would need to add these two lines to your Traefik config. This exposes the [API backend](https://docs.traefik.io/toml/#api-backend), which contains the web UI as well.
```
[web]
address = ":8080"
```

In order to access it, you'll also need to add port 8080 to the pod spec in traefik.yaml, as well as expose that port in the service spec.

Hope that helps!

**Comment by dstroot** [comment]
Yep - that worked along with an ingress for it.  That was a fast response!

**Comment by patrickeasters** [comment]
Awesome! Glad it worked. You timed your comment well--I can't say I'm always this responsive. 😄 

Happy Kubernetes/Traefik-ing!
